// <auto-generated />
using System;
using API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260619010838_start")]
    partial class start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.BusinessEntities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApartmentNumber")
                        .HasColumnType("int");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("int");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StreetId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.AvailableVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("VersionId");

                    b.ToTable("AvailableVersions");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LicenceId")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenceId")
                        .IsUnique()
                        .HasFilter("[LicenceId] IS NOT NULL");

                    b.HasIndex("SubscriptionId")
                        .IsUnique()
                        .HasFilter("[SubscriptionId] IS NOT NULL");

                    b.ToTable("Billings");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.BillingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BillingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "License"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Subscription"
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            SoftwareId = 1
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Company", b =>
                {
                    b.Property<string>("Krs")
                        .HasColumnType("nchar(10)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Krs");

                    b.HasIndex("AddressId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingId")
                        .HasColumnType("int");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("date");

                    b.Property<bool>("Signed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BillingId")
                        .IsUnique();

                    b.HasIndex("EntityId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("From")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Percent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BillingTypeId");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingTypeId = 1,
                            From = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Basic",
                            Percent = 33.3m,
                            To = new DateTime(2030, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Krs")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("Pesel")
                        .HasColumnType("nchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Krs")
                        .IsUnique()
                        .HasFilter("[Krs] IS NOT NULL");

                    b.HasIndex("Pesel")
                        .IsUnique()
                        .HasFilter("[Pesel] IS NOT NULL");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Invidual", b =>
                {
                    b.Property<string>("Pesel")
                        .HasColumnType("nchar(11)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Pesel");

                    b.HasIndex("AddressId");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YearsOfSupport")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(34)");

                    b.Property<int>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TransferredMoney")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.SoftDisc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftDiscs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountId = 1,
                            SoftwareId = 1
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Software", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Softwares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualVersion = "1.0.0",
                            Description = "C# IDE",
                            Name = "Rider"
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.SoftwareCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SoftwareCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Education"
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.SoftwareCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillingTypeId");

                    b.HasIndex("SoftwareId");

                    b.ToTable("SoftwareCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingTypeId = 1,
                            Price = 10000.00m,
                            SoftwareId = 1
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Version", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("date");

                    b.Property<int>("SoftwareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoftwareId");

                    b.ToTable("Versions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "0.9.0",
                            PublishDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "1.0.0",
                            PublishDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoftwareId = 1
                        });
                });

            modelBuilder.Entity("API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Worker"
                        });
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserName");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserName = "Admin",
                            ExpiresAt = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0,
                            PasswordHash = "AQAAAAIAAYagAAAAEHEF/gZKV53d1t2Yi7rjJJR9X+RSH7z7qNajMBmi/ZDGRXaCuBL0CFI0+SMsQ4IsvA==",
                            RefreshToken = "",
                            RoleId = 1
                        },
                        new
                        {
                            UserName = "Worker",
                            ExpiresAt = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id = 0,
                            PasswordHash = "AQAAAAIAAYagAAAAENx1VsgLhsq97yO7TiUbzrqchjs8cRvbhsgXlz8zfZlXQEaYcxYvlPCLaUFXAMuB/A==",
                            RefreshToken = "",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Address", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Street", "Street")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Street");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.AvailableVersion", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Contract", "Contract")
                        .WithMany("AvailableVersions")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.BusinessEntities.Version", "Version")
                        .WithMany("AvailableVersions")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Billing", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.License", "License")
                        .WithOne("Billing")
                        .HasForeignKey("API.Entities.BusinessEntities.Billing", "LicenceId");

                    b.HasOne("API.Entities.BusinessEntities.Subscription", "Subscription")
                        .WithOne("Billing")
                        .HasForeignKey("API.Entities.BusinessEntities.Billing", "SubscriptionId");

                    b.Navigation("License");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Category", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.SoftwareCategory", "SoftwareCategory")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.BusinessEntities.Software", "Software")
                        .WithMany("Categories")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");

                    b.Navigation("SoftwareCategory");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.City", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Company", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Address", "Address")
                        .WithMany("Companies")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Contract", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Billing", "Billing")
                        .WithOne("Contract")
                        .HasForeignKey("API.Entities.BusinessEntities.Contract", "BillingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.BusinessEntities.Entity", "Entity")
                        .WithMany("Contracts")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Billing");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Discount", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.BillingType", "BillingType")
                        .WithMany("Discounts")
                        .HasForeignKey("BillingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingType");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Entity", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Company", "Company")
                        .WithOne("Entity")
                        .HasForeignKey("API.Entities.BusinessEntities.Entity", "Krs");

                    b.HasOne("API.Entities.BusinessEntities.Invidual", "Individual")
                        .WithOne("Entity")
                        .HasForeignKey("API.Entities.BusinessEntities.Entity", "Pesel");

                    b.Navigation("Company");

                    b.Navigation("Individual");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Invidual", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Address", "Address")
                        .WithMany("Individuals")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Payment", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Contract", "Contract")
                        .WithMany("Payments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.SoftDisc", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Discount", "Discount")
                        .WithMany("SoftDiscs")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.BusinessEntities.Software", "Software")
                        .WithMany("SoftDiscs")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Software");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.SoftwareCost", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.BillingType", "BillingType")
                        .WithMany("SoftwareCosts")
                        .HasForeignKey("BillingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Entities.BusinessEntities.Software", "Softwares")
                        .WithMany("SoftwareCosts")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingType");

                    b.Navigation("Softwares");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Street", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.City", "City")
                        .WithMany("Streets")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Version", b =>
                {
                    b.HasOne("API.Entities.BusinessEntities.Software", "Software")
                        .WithMany("Versions")
                        .HasForeignKey("SoftwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Software");
                });

            modelBuilder.Entity("API.Entities.User", b =>
                {
                    b.HasOne("API.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Address", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Individuals");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Billing", b =>
                {
                    b.Navigation("Contract")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.BillingType", b =>
                {
                    b.Navigation("Discounts");

                    b.Navigation("SoftwareCosts");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.City", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Company", b =>
                {
                    b.Navigation("Entity")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Contract", b =>
                {
                    b.Navigation("AvailableVersions");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Discount", b =>
                {
                    b.Navigation("SoftDiscs");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Entity", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Invidual", b =>
                {
                    b.Navigation("Entity")
                        .IsRequired();
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.License", b =>
                {
                    b.Navigation("Billing");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Software", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("SoftDiscs");

                    b.Navigation("SoftwareCosts");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.SoftwareCategory", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Street", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Subscription", b =>
                {
                    b.Navigation("Billing");
                });

            modelBuilder.Entity("API.Entities.BusinessEntities.Version", b =>
                {
                    b.Navigation("AvailableVersions");
                });

            modelBuilder.Entity("API.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
